### ISSUE TITLE
Incorrect readings

### ISSUE THREAD

**Issue by itsupera** [SeasonedMiso/ImmersionTyping#1]
The idea is cool but IMHO it becomes frustrating because of incorrect readings.
For example 時 (as in 時に) must be typed じ when it should be とき instead.
I know that automatically getting the proper readings is hard, so maybe you could accept all the possible readings of a given word?

**Comment by SeasonedMiso** [comment]
Thank you for your feedback! I don't think that it is in the best interests of people who use this app to be able to enter readings that are incorrect in the current context, so having any reading work is not what I want to do going forward. In regards to 時に the context is actually 購入時＋に so the reading of じ is correct. If you find any other issues, feel free to let me know!
![image](https://user-images.githubusercontent.com/31320399/148453340-05389445-c39e-4f3f-a80a-e223f7b17ff0.png)
